// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for macos - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5Vitlm4m0HeeX2ZJp6IvhIG1xJlcPDS8',
    appId: '1:752904600547:android:580353e0f00d6d70097ed6',
    messagingSenderId: '752904600547',
    projectId: 'deliverytak',
    databaseURL: 'https://deliverytak-default-rtdb.firebaseio.com',
    storageBucket: 'deliverytak.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPN82WtFQHxvP-hIVA8ug9kK0mcOj27Wk',
    appId: '1:752904600547:ios:fcad75da46ee73f0097ed6',
    messagingSenderId: '752904600547',
    projectId: 'deliverytak',
    databaseURL: 'https://deliverytak-default-rtdb.firebaseio.com',
    storageBucket: 'deliverytak.appspot.com',
    androidClientId:
        '752904600547-3lqg84h4ff8uudsu1ct61vlssubnmnpu.apps.googleusercontent.com',
    iosClientId:
        '752904600547-qn94i0n4r98jseghfmkmea9obrl9qfae.apps.googleusercontent.com',
    iosBundleId: 'com.example.deliverytak',
  );
}
